### ISSUE TITLE
not an issue. (question)

### ISSUE THREAD

**Issue by freaky767** [agarian-2/agarian-2.github.io#1]
how can you connect to servers using wss, i have my cigar hosted on github.io, and it doesn't wanna connect at all..

**Comment by agarian-2** [comment]
Well if you go into main_out.js and CTRL+F for setServer, you'll find it there I believe

**Comment by agarian-2** [comment]
I should've done this a long time ago lol

**Comment by freaky767** [comment]
1 year ago KEK
