### ISSUE TITLE
Custom Game Key

### ISSUE THREAD

**Issue by xiaoyu5263** [agarian-2/agarian-2.github.io#4]
Hi,can you implement custom buttons? I can give you two dollars.

**Comment by agarian-2** [comment]
Uh well (very late response, but) the client already supports the following custom keys: `e, r, t, p, q, o, m, i, y, u, k, l, h, z, x, s, c, g, j, b, v, n`. Also dude why would you pay me for it?

**Comment by xiaoyu5263** [comment]
Because many players want to have their own customary keys, so.

**Comment by xiaoyu5263** [comment]
I am very optimistic about this project and hope to achieve skin.

**Comment by xiaoyu5263** [comment]
This project is very good, hope to achieve skin.

**Comment by agarian-2** [comment]
Thanks, but tbh don't count on it lol
And yeah, I'm gonna close this issue since I've listed what custom keys can be used.
