### ISSUE TITLE
Some BUG

### ISSUE THREAD

**Issue by xiaoyu5263** [agarian-2/agarian-2.github.io#6]
1.Hidden food option is not available.
2.When you enter the game for the first time, you can see the players on the whole map. If you click to start the game, you will lose control of your ball and run to the map center.
3.When you feed, you pause for a while before you continue to feed.
4.Sometimes when the client connects to the server, it does not display the current status (server player...).
5.When you refresh the game, the settings you change will be restored to their original state. Except for the name.

-（Translation content. Maybe it's wrong.）

**Comment by agarian-2** [comment]
Closing this issue, since these bugs are fixed now, except for #5. I will look into that. Also #3 is intentional.

**Comment by agarian-2** [comment]
The options not saving issue is now fixed.

**Comment by BBrethren** [comment]
**3.When you feed, you pause for a while before you continue to feed.**

I know you said this was intentional, but could you add an option to remove this if possible? It would be amazing to have the feed do it instantly instead of that delay for me.

Thanks for all your work.
